### ISSUE TITLE
Choose suitable server implementaion for OpenAPI

### ISSUE THREAD

**Issue by lewismc** [opengeospatial/LANDRS#7]
Yesterday we discussed the server implementation and @charlesvardeman stated a preference for NodeJS. I had no issues with that.
Unfortunately, as it turns out neither of the NodeJS openapi-generators are functional right now.
When I say both, I mean *graphql-nodejs-express-server* and *nodejs-server-deprecated*. When I generate with the former I get the following
```
npm start run

> graphql-server@1.0.0 start /Users/lmcgibbn/Downloads/LANDRS/DesignDocs/DesignHack1/openapi/openapi3graphql-server
> node start.js "run"


/Users/lmcgibbn/Downloads/LANDRS/DesignDocs/DesignHack1/openapi/openapi3graphql-server/node_modules/graphql/language/parser.js:1428
  throw (0, _syntaxError.syntaxError)(lexer.source, token.start, "Expected ".concat(kind, ", found ").concat((0, _lexer.getTokenDesc)(token)));
  ^
Syntax Error: Expected Name, found }

GraphQL request:18:1
17 | type Mutation {
18 | }
   | ^
19 |
    at syntaxError (/Users/lmcgibbn/Downloads/LANDRS/DesignDocs/DesignHack1/openapi/openapi3graphql-server/node_modules/graphql/error/syntaxError.js:15:10)
    at expectToken (/Users/lmcgibbn/Downloads/LANDRS/DesignDocs/DesignHack1/openapi/openapi3graphql-server/node_modules/graphql/language/parser.js:1428:38)
    at parseName (/Users/lmcgibbn/Downloads/LANDRS/DesignDocs/DesignHack1/openapi/openapi3graphql-server/node_modules/graphql/language/parser.js:91:15)
    at parseFieldDefinition (/Users/lmcgibbn/Downloads/LANDRS/DesignDocs/DesignHack1/openapi/openapi3graphql-server/node_modules/graphql/language/parser.js:863:14)
    at many (/Users/lmcgibbn/Downloads/LANDRS/DesignDocs/DesignHack1/openapi/openapi3graphql-server/node_modules/graphql/language/parser.js:1515:16)
    at parseFieldsDefinition (/Users/lmcgibbn/Downloads/LANDRS/DesignDocs/DesignHack1/openapi/openapi3graphql-server/node_modules/graphql/language/parser.js:852:54)
    at parseObjectTypeDefinition (/Users/lmcgibbn/Downloads/LANDRS/DesignDocs/DesignHack1/openapi/openapi3graphql-server/node_modules/graphql/language/parser.js:806:16)
    at parseTypeSystemDefinition (/Users/lmcgibbn/Downloads/LANDRS/DesignDocs/DesignHack1/openapi/openapi3graphql-server/node_modules/graphql/language/parser.js:704:16)
    at parseDefinition (/Users/lmcgibbn/Downloads/LANDRS/DesignDocs/DesignHack1/openapi/openapi3graphql-server/node_modules/graphql/language/parser.js:137:16)
    at many (/Users/lmcgibbn/Downloads/LANDRS/DesignDocs/DesignHack1/openapi/openapi3graphql-server/node_modules/graphql/language/parser.js:1515:16) {
  message: 'Syntax Error: Expected Name, found }',
  locations: [ { line: 18, column: 1 } ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! graphql-server@1.0.0 start: `node start.js "run"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the graphql-server@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/lmcgibbn/.npm/_logs/2019-07-11T14_25_52_899Z-debug.log
```
The latter is simply deprecated and should not be used anymore.

Therefore the question on the table is which other implementation do you guys want to use?

**Comment by lewismc** [comment]
@r4space @charlesvardeman FYI

**Comment by charlesvardeman** [comment]
Wow, that's somewhat bad that those generators are deprecated. 
So when I looked at this a while ago, I think some of the OGC OpenAPI hack-a-thon's were using [swagger-routes-express](https://www.npmjs.com/package/swagger-routes-express). Looking at the [Github readme](https://github.com/davesag/swagger-routes-express#readme), it supports OpenAPI V3. There is also some utility code developed by the same user including a [microservice generator](https://github.com/davesag/microservice-generator] and an [api server boilerplate](https://github.com/davesag/api-server-boilerplate) that already has a docker-compose integrated.  Have a look at the repo's and see what you think.

**Comment by lewismc** [comment]
Thanks for those references Chuck. I went ahead and chose the api server boilerplate you referenced above. 
More work to do on the OAS but we are getting closer.
